# Generated by Django 4.2.20 on 2025-04-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producttag', '0002_alter_tag_name_alter_tag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
