# Generated by Django 4.2.20 on 2025-06-24 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'در حال پرداخت'), (1, 'لغو شده'), (2, 'تحویل شده')], default=0)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('delivery_amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('paying_amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('paid', 'پرداخت شده'), ('pending', 'در انتظار پرداخت'), ('failed', 'پرداخت ناموفق')], default='pending', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('cerated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
