# Generated by Django 4.2.20 on 2025-06-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cerated_at',
            new_name='created_at',
        ),
    ]
