# Generated by Django 4.2.20 on 2025-06-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_cerated_at_order_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
